### ISSUE TITLE
Fails to build with ffmpg 8.0

### ISSUE THREAD

**Issue by lazka** [audaspace/audaspace#32]
```c
audaspace-1.7.0/plugins/ffmpeg/FFMPEGReader.cpp:288:49: error: use of undeclared identifier 'AV_INPUT_BUFFER_MIN_SIZE'
  288 |         m_membuf = reinterpret_cast<data_t*>(av_malloc(AV_INPUT_BUFFER_MIN_SIZE + AV_INPUT_BUFFER_PADDING_SIZE));
      |                                                        ^
C:/msys64/home/user/M/mingw-w64-audaspace/src/audaspace-1.7.0/plugins/ffmpeg/FFMPEGReader.cpp:290:47: error: use of undeclared identifier 'AV_INPUT_BUFFER_MIN_SIZE'
  290 |         m_aviocontext = avio_alloc_context(m_membuf, AV_INPUT_BUFFER_MIN_SIZE, 0, this, read_packet, nullptr, seek_packet);
      |                                                      ^
2 errors generated.
```

Here is the commit deprecating the now removed API, for context: https://github.com/FFmpeg/FFmpeg/commit/1d66a122df9fd5d8400b05c74462d0082990fc01
